name: Terraform Deploy

on:
  push:
    branches: ["ops/container-apps"]
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Login en Azure con Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 3. Exportar variables ARM para Terraform
      - name: Export Azure Credentials
        run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV

      # 4. Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 5. Inicializar (usa el backend remoto en Azure)
      - name: Terraform Init
        run: terraform init -no-color

      # 6. Validar sintaxis
      - name: Terraform Validate
        run: terraform validate -no-color

      # 7. Plan (con tfvars y secrets)
      - name: Terraform Plan
        run: terraform plan -no-color \
          -var-file="terraform.dev.tfvars" \
          -var "docker_username=${{ secrets.DOCKER_USERNAME }}" \
          -out=tfplan

      # 8. Apply
      - name: Terraform Apply
        run: terraform apply -no-color -auto-approve tfplan
